### ISSUE TITLE
Inertia v0.1.0 Field Testing!

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#105]
## ✈️ Purpose
This is a ticket to track field-testing deployment of various docker-compose projects using [Inertia](https://github.com/ubclaunchpad/inertia/)'s upcoming `v0.1.0` release, which will include some important features like branch management (#83) and Inertia versioning (#35) and hopefully be somewhat ready for live usage.

## 🚧 Test Outline
- set up target project for `docker-compose`
- provide instructions and guidance on how to use Inertia with project
- collect feedback, bug reports, etc.

## 🤔 Target Projects
- [ubclaunchpad/rocket](https://github.com/ubclaunchpad/rocket) @bfbachmann @jordanschalm 
   - [ ] [Inertia usage ticket](https://github.com/ubclaunchpad/rocket/issues/45)
- [ubclaunchpad/bumper](https://github.com/ubclaunchpad/bumper) @ubclaunchpad/appvengers
   - [x] [docker-compose PR](https://github.com/ubclaunchpad/bumper/pull/98)
   - [x] Amazon ECS needs custom setup #108 
   - [x] Something wrong with how repos update #110 
   - [ ] Logs are kind of bad #109

**Comment by bobheadxi** [comment]
We're pretty far from v0.1.0 now - closing this ticket
