### ISSUE TITLE
Inertia Web 1.0

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#204]
This project will involve a complete redesign and rewrite of Inertia Web to bring it to feature parity with the command line application and enable improved team features for the Inertia platform. Inertia branding will probably also be updated.

## Roadmap

- [x] Wireframe web app and update Inertia branding (#160)
- [x] Scaffold implementation of updated design (#248)
- [ ] Add functionality until feature parity with CLI is achieved

**Comment by bobheadxi** [comment]
Closing as this is now a dupe of #248, opened by @PiggySpeed

**Comment by bobheadxi** [comment]
Reopening because this is not quite a dupe :p

**Comment by bobheadxi** [comment]
closing, as we are moving away from zenhub
