### ISSUE TITLE
Inertia Platform 1.0

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#205]
This project involves fleshing out and improving existing features as well as implementing new functionality with the goal of solidifying Inertia's position as a robust, portable, and feature-rich continuous deployment **platform**.

## Roadmap

- [ ] Fix any issues that might block work on #204 and finalize API
- [ ] Implement remaining priority features - custom ENV, build and deploy notifications, log archival, 
- [ ] Smooth over any remaining kinks with deployment and improve if possible
- [ ] Improve UX - CLI experience, log formatting, etc.
- [ ] Implement remaining features we might deem suitable for a v1.0.0 release.

**Comment by bobheadxi** [comment]
closing, as we are moving away from zenhub
