### ISSUE TITLE
web: cleanup

### ISSUE THREAD

**Issue by mRabitsky** [ubclaunchpad/inertia#543]
Spring cleaning: update and convert various parts of the front end to a more modern/succinct approach.

- [x] Convert to **create-react-app** (see: #542)
- [x] Convert to SCSS
- [ ] Arrange & rearrange structure
- [ ] Convert to TypeScript (time-permitting)
