### ISSUE TITLE
all: go1.13

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#611]
https://github.com/golang/go/milestone/83
https://docs.google.com/presentation/d/e/2PACX-1vRo5urog_B76BcnQbIo7I391MZUKFj7l3gku6hypJ-WK1KCFw40A7BiM6NOVsqD17sA9jS7GyzCfnN4/pub

- [ ] switch to modules (#619)
- [x] bump CI/CD (#617)
- [x] use [UserConfigDir](https://github.com/golang/go/issues/29960) instead of the homepath (#618)
