### ISSUE TITLE
release: inertia v0.6.1

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#673]
**Milestone**

https://github.com/ubclaunchpad/inertia/milestone/13

**Tasks**

* [x] make sure https://github.com/ubclaunchpad/rocket2/pull/451 happens smoothly and any issues get fixed in this release (/cc @cheukyin699)

Make a new PR:

* [x] generate release documentation (`make docs`)
* [x] generate new tip documentation (`make docs-tip`)

Update distribution streams:

* [x] draft changelog
* [ ] make release and let builds run
* [ ] update https://github.com/ubclaunchpad/homebrew-tap
* [ ] update https://github.com/ubclaunchpad/scoop-bucket
* [ ] run `npm publish` in `contrib/npm`

---

**Draft Changelog**

![Publish (release)](https://github.com/ubclaunchpad/inertia/workflows/Publish%20(release)/badge.svg) ![Publish (latest)](https://github.com/ubclaunchpad/inertia/workflows/Publish%20(latest)/badge.svg)

This release includes some fixes and adjustments to [v0.6.0](https://github.com/ubclaunchpad/inertia/releases/tag/v0.6.0).

## 🎉 Enhancements

* a new field, `version`, has been added to project configuration denoting the minimum required Inertia CLI version, and a warning will now show when this version is invalid (#670)
* `inertia ${remote} status` will now include details on new Inertia releases that are available (#666)
* `docker-compose` versions now automatically pull the latest valid tag (#667)

## ⚒ Fixes 

* some prompts are now clearer (#663) 
* fixed a bug where `inertia project set` does not update configuration correctly (#669)  
* fixed a bug where `inertia ${remote} upgrade` does not update configuration correctly (#668) 

---

Please refer to the [complete diff](https://github.com/ubclaunchpad/inertia/compare/v0.6.0...v0.6.1) for more details.
