### ISSUE TITLE
release: inertia v0.6.2

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#690]
**Milestone**

https://github.com/ubclaunchpad/inertia/milestones/v0.6.2

**Tasks**

Make a new PR and merge when everything is ready:

* [x] generate release documentation (`make docs`)
* [x] generate new tip documentation (`make docs-tip`)

Update distribution streams:

* [x] draft changelog
* [x] make release and let builds run
* [x] update [`ubclaunchpad/homebrew-tap`](https://github.com/`ubclaunchpad/homebrew-tap)
* [x] update [`ubclaunchpad/scoop-bucket`](https://github.com/ubclaunchpad/scoop-bucket)

---

**Draft Changelog**

![Publish (release)](https://github.com/ubclaunchpad/inertia/workflows/Publish%20(release)/badge.svg) ![Publish (latest)](https://github.com/ubclaunchpad/inertia/workflows/Publish%20(latest)/badge.svg)

Minor polish and some internal changes.

## ⚠️ Breaking Changes

* The npm distribution for the Inertia CLI will no longer be published ([#688](https://github.com/ubclaunchpad/inertia/pull/688))

## ⚒ Fixes 

* Removed a debug log for version constraints ([#687](https://github.com/ubclaunchpad/inertia/pull/687))

---

Please refer to the [complete diff](https://github.com/ubclaunchpad/inertia/compare/v0.6.1...v0.6.2) for more details.
