### ISSUE TITLE
release: inertia v0.7.0

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#706]
**Milestone**

https://github.com/ubclaunchpad/inertia/milestones/v0.7.0

**Tasks**

Make a new PR and merge when everything is ready:

* [x] generate release documentation (`make docs`)
* [x] generate new tip documentation (`make docs-tip`)

Update distribution streams:

* [x] draft changelog using template below
* [ ] publish GitHub release with the changleog and let pipelines run
* [ ] ensure release is live in [releases](https://github.com/ubclaunchpad/inertia/releases), [packages](https://github.com/orgs/ubclaunchpad/packages/container/package/inertiad), [`ubclaunchpad/homebrew-tap`](https://github.com/`ubclaunchpad/homebrew-tap), and [`ubclaunchpad/scoop-bucket`](https://github.com/ubclaunchpad/scoop-bucket)

---

**Draft Changelog**

![Publish (release)](https://github.com/ubclaunchpad/inertia/workflows/Publish%20(release)/badge.svg) [![Docs](https://img.shields.io/website?label=docs&up_message=live&url=https%3A%2F%2Finertia.ubclaunchpad.com)](https://inertia.ubclaunchpad.com)

This release features improvements in using Inertia accounts with login-related commands and other CLI improvements, as well as a switch away from Docker Hub for Inertia daemon images that necessitates a breaking change.

## ⚠️ Breaking Changes

* Older Inertia daemon images (pre-`v0.6.2`) are now no longer supported, since the Inertia CLI now bootstraps remotes using our new [GitHub Container Registry images](https://github.com/orgs/ubclaunchpad/packages/container/package/inertiad) (#692, #708)

## 🎉 Enhancements

* Now building with go1.15 (#693)
* New `inertia remote import` command to import existing remote configuration (#703)
* The username last used to log in is now saved in remote configuration (#702) 

## ⚒ Fixes 

* Misc. output and formatting fixes (#701 , etc)

---

Please refer to the [complete diff](https://github.com/ubclaunchpad/inertia/compare/v0.6.2...v0.7.0) for more details.

**Comment by bobheadxi** [comment]
![image](https://user-images.githubusercontent.com/23356519/96546850-9d3c9e00-12dd-11eb-8837-8b91c7c33a5d.png)

yeet
