### ISSUE TITLE
Inertia Web

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#73]
Would be cool to offer a clean web interface for managing your Inertia project when the daemon is online:
```
$> inertia myremote init
...
Inertia daemon is now online. Visit http://myhost.com:8081/admin to manage your project!
```

At minimum, the user should be able to:
- [ ] enable more accounts from the CLI and allow logins via web interfaces
- [ ] be assured of the security of using inertia web
- [ ] manage the deployment state of their project (up/down)
- [ ] manage their repository (change branches, check what commit is deployed)
- [ ] view things like docker-compose logs and container logs

Stretch goals:
- Analytics? Visitor count, deploys per day, uptime/downtime
- Container backups?
- Plugins?

**Comment by PiggySpeed** [comment]
UI ideas: https://portainer.io/overview.html

**Comment by bobheadxi** [comment]
MVP done as of v0.3.0 - closing this ticket
